# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    # Raise pull requests for version updates on `master` branch
    target-branch: "main"
    schedule:
      interval: "daily"
      # Check for npm updates at 0815hrs UTC
      time: "08:15"
    # Allow up to N open pull requests (independant of source)
    open-pull-requests-limit: 50

  - package-ecosystem: "gradle"
    # Any gradle based dependencies
    directories:
      - "/"
      - "/app"
      - "/extensions/deepnetts"
      - "/extensions/dflib"
      - "/extensions/file"
      - "/extensions/langchain4j"
      - "/shell"
      - "/ui"
    # Raise pull requests for version updates on `master` branch
    target-branch: "main"
    schedule:
      interval: "daily"
      # Check for npm updates at 0815hrs UTC
      time: "08:15"
    # Group Update PRs
    groups:
      javafx:
        patterns:
          - "org.openjfx:javafx-*"
    # Allow up to N open pull requests (independant of source)
    open-pull-requests-limit: 50
